### ISSUE TITLE
Cannot build example code using the latest VoicePing SDK

### ISSUE THREAD

**Issue by anta40** [SmartWalkieOrg/VoicePing-Walkie-Talkie-AndroidSDK#13]
I'm using the latest SDK, and it seems that the example app somehow doesn't sync with it.
Example: in LoginActivity, you'll see this:
`VoicePing.connect(serverUrl, userId, company, object : ConnectCallback`

I highlighted the `connect` function, and Android Studio only showed 3 params: `userId`, `company`, and a callback. So that's a syntax error, and gotta removed the `serverUrl` param.

So this is my attempt to produce a working example: https://github.com/anta40/VoicePingDemo. Basically a mere copy of the example, with some function calls corrected.
At least it's now compilable (I'm on Android Studio Electric Eel), but won't run, due to these errors:
```
Process: com.smartwalkie.voicepingdemo, PID: 3463
java.lang.ExceptionInInitializerError
at com.smartwalkie.voicepingdemo.MainActivity.onCreate(MainActivity.kt:44)
at android.app.Activity.performCreate(Activity.java:8051)
at android.app.Activity.performCreate(Activity.java:8031)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3612)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3796)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7842)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Caused by: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized
at com.smartwalkie.voicepingdemo.VoicePingClientApp$Companion.getContext(VoicePingClientApp.kt:27)
at com.smartwalkie.voicepingdemo.MyPrefs.<clinit>(MyPrefs.kt:8)
at com.smartwalkie.voicepingdemo.MainActivity.onCreate(MainActivity.kt:44) 
at android.app.Activity.performCreate(Activity.java:8051) 
at android.app.Activity.performCreate(Activity.java:8031) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
```

**Comment by adityawibisana** [comment]
Please recheck the error again. It's on your own implementation, not related with error on our repository code

`VoicePingClientApp.kt:27`

**Comment by adityawibisana** [comment]
VoicePingClientApp was meant to be the first hook on when your application start. 
Because you created your own app, then feel free to remove "VoicePingClientApp", and move all of the code there to your app's code.
